### ISSUE TITLE
Motion Sensor entities cannot be changed

### ISSUE THREAD

**Issue by sambarlick** [Hankanman/Area-Occupancy-Detection#14]
### Prerequisites

* [X] I have checked that this issue has not already been reported
* [X] I am running the latest version of the integration
* [ ] I have checked the Home Assistant logs for relevant errors

### Description

I cannot change Motion Sensor entities. I can change all other entities in other categories. I have deleted the areas that need the sensors changed created before the 2024.12 update and the issue still exists in areas created after the 2024.12 update.
### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

Change, add or delete motion sensors
**Actual behavior:**

The changes are submitted but then the have not stored and I go back into edit the area and nothing has changed.
### Debug Information

**Home Assistant version:**

**Integration version:**

**Integration configuration:**

* [X] Motion sensors
* [ ] Media devices
* [ ] Appliances
* [ ] Illuminance sensors
* [ ] Humidity sensors
* [ ] Temperature sensors

**Relevant logs:**
```
# Copy relevant logs from Home Assistant
```

### Additional Context

[area_error_log.txt](https://github.com/user-attachments/files/18147120/area_error_log.txt)

**Comment by Hankanman** [comment]
Thanks for reporting, I can see the issue should have a fix tomorrow
