### ISSUE TITLE
Area Occupancy Detection - Device selection dropdown not properly populated

### ISSUE THREAD

**Issue by skarl99** [Hankanman/Area-Occupancy-Detection#3]
### Prerequisites

* [ ] Ikea Zigbee Vallhorn motions
* [ ] Output from Home Assistant Developer Tools state e.g.
* [ ] Output from Home Assistant Device Diagnostic from BT

```json
{
  YOUR DEVICE DIAGNOSTICS JSON OUTPUT HERE
}
```

### Description

when selecting the motion detector drop down, or the illumance drop down selection, it is not populating the motion or illumance binary sensors for the zigbee devices. it is however populating other motion and illumance devices like my hardwired alarm system devices and x10 devices.

### Steps to Reproduce

1. select drop down
2. start typing kitchen
3. limited kitchen devices shown (2 of the 3 that are in the room)

**Expected behavior:**

3 kitchen motion devices should be shown

**Actual behavior:**

Only 2 devices shown. None of the zigbee motion or illumance sensors will appear.

### Versions

HA 2024.12.2
Area Occupance Detection V1.0.0

**Comment by skarl99** [comment]
![Kitchen motion list](https://github.com/user-attachments/assets/50a92290-dae5-4e73-8660-84e14f43f564)
![Kitchen motion selection](https://github.com/user-attachments/assets/a5381f33-d2c9-425a-bc47-567b22d00230)
![Kitchen illumance selection](https://github.com/user-attachments/assets/845fc04d-7901-462d-a01d-91f19ec3aaf6)

here are some screen captures that may be of assistance.

**Comment by z0gst** [comment]
I have a similar issue.
There is no motion sensors to be selected at all:

![image](https://github.com/user-attachments/assets/4d135358-a47e-4a70-89a3-8eebe289fdb0)

However I can add the name of the sensor manually and that seems to recognise it:

![image](https://github.com/user-attachments/assets/244f05ed-e71f-47a1-b17c-fb90524753e2)
![image](https://github.com/user-attachments/assets/7d9d6e63-06c3-4413-ae35-c2dcc4286d33)

All the other sensors seem to populate dropdown menus correctly.
