### ISSUE TITLE
Aqara FP1 and FP2 sensors not working also EPL.

### ISSUE THREAD

**Issue by deiniolj** [Hankanman/Area-Occupancy-Detection#6]
When selecting from the dropdown, I thought these Presence Sensors would appear.

Aqara FP2 Presence Sensor
Aqara FP1ePresense Senor
EPLite 

Seems to only see my Aqara P1 Motion Sensors.

**Comment by deiniolj** [comment]
Is it because I bring them in as Matter devices in HA..

**Comment by Hankanman** [comment]
This is due to the entity filters on the inputs, I will check the device class for mmwave sensors and allow them for the next release, for now you can try entering the complete entity id like "binary_sensor.fp2_occupancy" for example
