### ISSUE TITLE
 Add device class Occupancy

### ISSUE THREAD

**Issue by Alxrs84** [Hankanman/Area-Occupancy-Detection#7]
### Description

The current implementation of the Area Occupancy Detection integration requires at least one sensor with the device_class set to "motion" for each area configuration. However, many mmWave occupancy sensors and similar devices are configured with the device_class set to "occupancy" by default, which makes them incompatible with the current configuration requirements of the integration.

To enhance usability and compatibility, the integration should be updated to allow sensors with the device_class "occupancy" to be included in the area configuration. The updated implementation should permit at least one sensor with either the device_class "motion" or the device_class "occupancy" to fulfill the configuration requirements for an area.

This feature will significantly improve the integration's utility, as occupancy sensors are highly accurate and reliable for determining room occupancy.

### Additional Information

The feature should ensure backward compatibility by maintaining the current support for "motion" device class sensors.
Many mmWave occupancy sensors are widely used in smart home setups, and their inclusion would align with industry standards and user expectations.
Example devices that use device_class "occupancy":
Aqara Human Presence Sensor FP1
Tuya mmWave Presence Sensors
A potential validation rule could check if the configuration contains at least one sensor with device_class "motion" or "occupancy" per area.
This enhancement would allow users to leverage advanced presence detection capabilities provided by mmWave occupancy sensors, making the integration more robust and versatile.

**Comment by Alxrs84** [comment]
One could assume that an occupancy sensor makes this integration superfluous, as the occupancy sensor already determines the occupancy of an area itself. Nevertheless, here is a use case that supports the feature request:

- Large area with more than one occupancy sensor (e.g. floor). I would like to determine whether a floor is occupied, for this I have an occupancy sensor in each room. If one of these detects an occupancy, the entire floor should be considered occupied.

I know that this could also be realized using template sensors or groups. However, I had hoped that I could map everything relating to occupancy within this integration.

**Comment by Hankanman** [comment]
That is the goal, it is also targeted at learning from your history. I will update the device classes in the next release

**Comment by Hankanman** [comment]
> I was just looking at this integration and noticed the same lack. Is there a reason why you don't just allow any binary_sensor? I think I'm somewhat missing the point of this vs the normal Bayesian sensor?

The next release will have occupancy and motion in one category and regular binary sensors in another, these are separate purposefully because motion and occupancy are the "most reliable" indicators of past occupancy. This is what makes the integration different, you don't need to figure out all your priors and probabilities, it uses your real historic sensor data to do that for you, in near real time. It does a final bayesian calculation at the end of everything to get your final probabilities
