### ISSUE TITLE
Bad link in the README.md

### ISSUE THREAD

**Issue by hsrthe4th** [Hankanman/Area-Occupancy-Detection#9]
### Prerequisites

* [ ] Model name of your Devices
* [ ] Output from Home Assistant Developer Tools state e.g.
* [ ] Output from Home Assistant Device Diagnostic from BT

```json
{
  N/A
}
```

### Description

The link in "Join our [Community Discussion](https://github.com/Hankanman/Area-Occupancy-Detection/discussions)" is a dead link

I think there are also bad references in the New Issue chooser section
These three all lead to a different github repo/ discord

- Report a bug with the UI, Frontend
- I have a question or need support
- I'm unsure where to go

1. Click the link https://github.com/Hankanman/Area-Occupancy-Detection/discussions
2. 
3. 

**Expected behavior:**

A github discussion forum should open

**Actual behavior:**

Github 404

**Comment by Hankanman** [comment]
Yep I didn't expect anyone to notice the integration until it got accepted onto hacs, I'll get that updated in the morning

**Comment by hsrthe4th** [comment]
no worries, you were highlighted by BeardedTinker on youtube

**Comment by Hankanman** [comment]
Fixed! Thanks for pointing it out
